CREATE SCHEMA IF NOT EXISTS test_schema;
USE test_schema;
GRANT REPLICATION SLAVE, REPLICATION CLIENT, SELECT, PROCESS ON *.* TO 'replicant'@'192.168.0.0/255.255.255.0' IDENTIFIED BY 'AVPP7WKANP55BTUP';
GRANT REPLICATION SLAVE, REPLICATION CLIENT, SELECT, PROCESS ON *.* TO 'replicant'@'localhost' IDENTIFIED BY 'AVPP7WKANP55BTUP';
GRANT DELETE, INSERT, SELECT, UPDATE ON test_schema.* TO 'testeradmin'@'%' IDENTIFIED BY 'FZ6CQZTPYHVFAYGQ!';
GRANT SELECT ON test_schema.* TO 'tester'@'%' IDENTIFIED BY 'Tester321!';
SELECT "xxxtestxxx";