apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app: reporting-mysql
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: reporting-mysql
  labels:
    app: reporting-mysql
spec:
  ports:
    - port: 3306
  selector:
    app: reporting-mysql
    tier: mysql
  clusterIP: None
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: reporting-mysql
  labels:
    app: reporting-mysql
spec:
  selector:
    matchLabels:
      app: reporting-mysql
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: reporting-mysql
        tier: mysql
    spec:
      containers:
      - image: mysql:5.6
        name: reporting-mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-root-pass
              key: mysql_root_password
        - name: MYSQL_USER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-user-pass
              key: mysql_password
        - name: MYSQL_USER_NAME
          valueFrom:
            secretKeyRef:
              name: mysql-user-pass
              key: mysql_user
        ports:
        - containerPort: 3306
          name: reporting-mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim