apiVersion: v1
kind: Service
metadata:
  name: reporting-tool
spec:
  type: NodePort
  selector:
    app: reporting-tool
  ports:
    - port: 80 # expose the service on internal port 80
      targetPort: 5000 # our NodeJS app listens on port 5000
      nodePort: 30000 # our NodeJS app will be exposed at 30000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reporting-tool
  annotations: 
    date: 2019-07-24
spec:
  replicas: 2
  selector:
    matchLabels:
      app: reporting-tool
  template:
    metadata:
      labels:
        app: reporting-tool
    spec:
      containers:
      - name: reporting-tool
        image: cloud.canister.io:5000/kmurphs/reporting-tool-microservice
        ports:
          - containerPort: 5000
        env:
        - name: MYSQL_DB_HOST
          value: reporting-mysql-read
        - name: MYSQL_DB_USER
          value: tester
        - name: MYSQL_DB_NAME
          value: test_schema
        - name: MYSQL_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: reporting-mysql-pass
              key: mysql_tester_password
      imagePullSecrets:
         - name: canister-cred # secret that K8s uses to access image